# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Instalação do NuGet
- task: NuGetToolInstaller@1

# Restauração de pacotes
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build do projeto e criação do pacote de deploy
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)/WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publicação do pacote como um artefato
- publish: $(build.artifactStagingDirectory)/WebApp.zip
  artifact: WebAppArtifact

# Execução de testes
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Deploy para o Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students (10b15b88-8a07-4ad9-bf08-e557ed8f5519)'
    appType: 'webApp'
    appName: 'globalsolution-fiap'
    package: '$(System.DefaultWorkingDirectory)/WebAppArtifact/WebApp.zip'
    deploymentMethod: 'auto'