trigger:
- master

pool:
  vmImage: 'windows-latest'

# Inclui o grupo de variáveis e define variáveis adicionais de build
variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - group: AzureCredentialsGroup  # Adiciona o grupo de variáveis seguras

steps:
# Etapa 1: Instala o SDK do .NET 5.x
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Etapa 2: Restaura os pacotes NuGet para o projeto
- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'  # Encontra e restaura pacotes para todos os arquivos .sln no projeto

# Etapa 3: Compila o projeto usando o Visual Studio Build
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'  # Compila todos os arquivos de solução (.sln) no repositório
    platform: '$(buildPlatform)'  # Usa a plataforma definida na variável `buildPlatform`
    configuration: '$(buildConfiguration)'  # Usa a configuração de build definida na variável `buildConfiguration`

# Etapa 4: Publica o projeto para gerar os artefatos de deploy
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'  # Comando de publicação do .NET CLI
    publishWebProjects: true  # Publica todos os projetos web no repositório
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'  # Define a saída para o diretório de artefatos

# Etapa 5: Faz login no Azure usando as variáveis seguras
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure for Students (10b15b88-8a07-4ad9-bf08-e557ed8f5519)'  # Nome da Service Connection no Azure DevOps
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Realizando login no Azure..."
      # Autenticação no Azure usando as variáveis seguras
      az login --service-principal -u $(azureClientId) -p $(azureClientSecret) --tenant $(azureTenantId)

# Etapa 6: Realiza o deploy do projeto no Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students (10b15b88-8a07-4ad9-bf08-e557ed8f5519)'  # Nome da sua Service Connection configurada no Azure DevOps
    appName: 'globalsolution-fiap'  # Nome do Azure Web App onde o projeto será implantado
    package: '$(Build.ArtifactStagingDirectory)'  # Caminho dos artefatos de publicação gerados na etapa de publicação
